put #gag  {^Chatter\[(Adammah|Adele|Aliyaha|Aslana|Avronah|Ayitz|Blaydz|Blossom|Catillia|Dwindella|Fredrickka|Gallak|Gonifa|Junipur|Kadosha|Kesefa|Kupatholim|Kydosha|Lavara|Lvana|Mabonn|Matlina|Maelistalyah|Mikkai|Mintlasa|Mushee|Negev|Nightshaydz|Nixx|Pipsqueek|Rashi|Rayfuah|Sapkarl|Shayddow|Shoshannah|Shvartzgonif|Slythher|Smozhstalker|Sunshyne|Totendanz|Verdrey|Wulvana|Yacov|Yehudit)\].*} {gonifgag}
put #gag  {^(Adammah|Adele|Aliyaha|Aslana|Avronah|Ayitz|Blaydz|Blossom|Catillia|Dwindella|Fredrickka|Gallak|Gonifa|Junipur|Kadosha|Kesefa|Kupatholim|Kydosha|Lavara|Lvana|Mabonn|Matlina|Maelistalyah|Mikkai|Mintlasa|Mushee|Negev|Nightshaydz|Nixx|Pipsqueek|Rashi|Rayfuah|Sapkarl|Shayddow|Shoshannah|Shvartzgonif|Slythher|Smozhstalker|Sunshyne|Totendanz|Verdrey|Wulvana|Yacov|Yehudit) thinks:.*} {gonifgag}
put #gag  {^(Adammah|Adele|Aliyaha|Aslana|Avronah|Ayitz|Blaydz|Blossom|Catillia|Dwindella|Fredrickka|Gallak|Gonifa|Junipur|Kadosha|Kesefa|Kupatholim|Kydosha|Lavara|Lvana|Mabonn|Matlina|Maelistalyah|Mikkai|Mintlasa|Mushee|Negev|Nightshaydz|Nixx|Pipsqueek|Rashi|Rayfuah|Sapkarl|Shayddow|Shoshannah|Shvartzgonif|Slythher|Smozhstalker|Sunshyne|Totendanz|Verdrey|Wulvana|Yacov|Yehudit)(.*) (whispers|says|asks|exclaims)( you| to \w+)*, (\".+([\.\?\!])\")} {gonifgag}
put #gag {\* [\S ]*(Adammah|Adele|Aliyaha|Aslana|Avronah|Ayitz|Blaydz|Blossom|Catillia|Dwindella|Fredrickka|Gallak|Gonifa|Junipur|Kadosha|Kesefa|Kupatholim|Kydosha|Lavara|Lvana|Mabonn|Matlina|Maelistalyah|Mikkai|Mintlasa|Mushee|Negev|Nightshaydz|Nixx|Pipsqueek|Rashi|Rayfuah|Sapkarl|Shayddow|Shoshannah|Shvartzgonif|Slythher|Smozhstalker|Sunshyne|Totendanz|Verdrey|Wulvana|Yacov|Yehudit) [\S ]*(joins the adventure|just crawled into the adventure|snuck out of the shadow she was hiding in).} {gonifgag}
put #gag {\* (Adammah|Adele|Aliyaha|Aslana|Avronah|Ayitz|Blaydz|Blossom|Catillia|Dwindella|Fredrickka|Gallak|Gonifa|Junipur|Kadosha|Kesefa|Kupatholim|Kydosha|Lavara|Lvana|Mabonn|Matlina|Maelistalyah|Mikkai|Mintlasa|Mushee|Negev|Nightshaydz|Nixx|Pipsqueek|Rashi|Rayfuah|Sapkarl|Shayddow|Shoshannah|Shvartzgonif|Slythher|Smozhstalker|Sunshyne|Totendanz|Verdrey|Wulvana|Yacov|Yehudit) was just struck down\!} {gonifgag}
put #gag {\* (Adammah|Adele|Aliyaha|Aslana|Avronah|Ayitz|Blaydz|Blossom|Catillia|Dwindella|Fredrickka|Gallak|Gonifa|Junipur|Kadosha|Kesefa|Kupatholim|Kydosha|Lavara|Lvana|Mabonn|Matlina|Maelistalyah|Mikkai|Mintlasa|Mushee|Negev|Nightshaydz|Nixx|Pipsqueek|Rashi|Rayfuah|Sapkarl|Shayddow|Shoshannah|Shvartzgonif|Slythher|Smozhstalker|Sunshyne|Totendanz|Verdrey|Wulvana|Yacov|Yehudit) has disconnected.} {gonifgag}
put #gag {\* (Adammah|Adele|Aliyaha|Aslana|Avronah|Ayitz|Blaydz|Blossom|Catillia|Dwindella|Fredrickka|Gallak|Gonifa|Junipur|Kadosha|Kesefa|Kupatholim|Kydosha|Lavara|Lvana|Mabonn|Matlina|Maelistalyah|Mikkai|Mintlasa|Mushee|Negev|Nightshaydz|Nixx|Pipsqueek|Rashi|Rayfuah|Sapkarl|Shayddow|Shoshannah|Shvartzgonif|Slythher|Smozhstalker|Sunshyne|Totendanz|Verdrey|Wulvana|Yacov|Yehudit) {gonifgag}

put #save all

